class=com.drskunk.sh3dlasercut.LasercutExportPlugin
name=Lasercut Export
description=Export a level as a lasercut SVG with box joint connections
version=2.0.0
license=GPL v2 or later
provider=DrSkunk
applicationMinimumVersion=4.0
javaMinimumVersion=1.8
